import { Application, ApplicationStatus, InternshipType, Role, SalaryType, WorkMode } from "@/types/types";

export const mockApplications: Application[] = [
  {
    id: "1",
    student: {
      id: "771d56c6-7802-4f7c-bc80-4ec97a4ddd59",
      role: Role.STUDENT,
      createdAt: new Date("2025-04-15T02:40:50.990826"),
      updatedAt: new Date("2025-04-15T02:40:50.990826"),
      email: "achrafbnr2406@gmail.com",
      firstName: "Achraf",
      lastName: "EL BANOURI",
      profilePicture: undefined,
      profileTitle: undefined,
      school: undefined,
      tel: undefined,
      location: null,
      links: {
        linkedin: undefined,
        github: undefined,
        cv: undefined,
        website: undefined,
      },
      profileDescription: null,
      experiences: [],
      formations: [],
      projects: [],
      certificates: [],
    },
    internship: {
      id: "1",
      title: "Frontend Developer",
      company: {
        id: "1",
        name: "TechCorp",
        profilePicture: "/user.png",
        location: {
          address: "123 Main St",
          city: "San Francisco",
          country: "USA",
        },
        applicationDate: new Date("2025-01-01"),
        description: "A leading tech company",
        ice: "123456",
        rc: "78910",
        phone: "123-456-7890",
        size: "100-500",
        createdAt: new Date("2025-01-01"),
        updatedAt: new Date("2025-01-01"),
        email: "info@techcorp.com",
        role: Role.COMPANY,
        internships: [],
      },
      createdAt: new Date("2025-04-01"),
      updatedAt: new Date("2025-04-01"),
      description: "Develop and maintain frontend applications.",
      duration: 6,
      salary: 5000,
      salaryType: SalaryType.MONTH,
      domain: "Web Development",
      workMode: WorkMode.REMOTE,
      tags: [InternshipType.PFE],
      skills: ["React", "JavaScript", "CSS"],
      negotiable: true,
      paid: true,
      likes: [],
      applicants: [],
    },
    status: ApplicationStatus.REJECTED,
    applicationDate: new Date("2025-04-15T02:40:50.990826"),
    motivationLetter: "",
    cv: "/CV/CV_ACHRAF_ELBANOURI_vEN.pdf",
  },
  // Add more applications here
];