import { Internship, InternshipType, Role, SalaryType, Student, WorkMode } from "@/types/types";

export const mockInternships: Internship[] = [
    {
        id: "1",
        title: "Frontend Developer",
        company: {
            id: "1",
            name: "TechCorp",
            profilePicture: "/user.png",
            location: {
                address: "123 Main St",
                city: "San Francisco",
                country: "USA",
            },
            applicationDate: new Date("2025-01-01"),
            description: "A leading tech company",
            ice: "123456",
            rc: "78910",
            phone: "123-456-7890",
            size: "100-500",
            createdAt: new Date("2025-01-01"),
            updatedAt: new Date("2025-01-01"),
            email: "info@techcorp.com",
            role: Role.COMPANY,
            internships: [],
        },
        createdAt: new Date("2025-04-01"),
        updatedAt: new Date("2025-04-01"),
        description: "Develop and maintain frontend applications.",
        duration: 6,
        salary: 5000,
        salaryType: SalaryType.MONTH,
        domain: "Web Development",
        workMode: WorkMode.REMOTE,
        tags: [InternshipType.PFE],
        skills: ["React", "JavaScript", "CSS"],
        negotiable: true,
        paid: true,
        likes: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        applicants: [{id : "1"} ,{id :"2"}] as Student[],
    },
    {
        id: "2",
        title: "Backend Developer",
        company: {
            id: "2",
            name: "CodeBase",
            profilePicture: "/user.png",
            location: {
                address: "456 Elm St",
                city: "New York",
                country: "USA",
            },
            applicationDate: new Date("2025-02-01"),
            description: "A software development company",
            ice: "654321",
            rc: "10987",
            phone: "987-654-3210",
            size: "50-200",
            createdAt: new Date("2025-02-01"),
            updatedAt: new Date("2025-02-01"),
            email: "contact@codebase.com",
            role: Role.COMPANY,
            internships: [],
        },
        createdAt: new Date("2025-03-28"),
        updatedAt: new Date("2025-03-28"),
        description: "Build and maintain backend systems.",
        duration: 6,
        salary: 6000,
        salaryType: SalaryType.MONTH,
        domain: "Backend Development",
        workMode: WorkMode.ON_SITE,
        tags: [InternshipType.PFA],
        skills: ["Node.js", "Express", "MongoDB"],
        negotiable: false,
        paid: true,
        likes: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
        applicants: [],
    },
];