import { Company } from "@/types/types";

export const universitiesSchools = [
  { name: "Université Mohammed V de Rabat", type: "university" },
  { name: "Université Hassan II de Casablanca", type: "university" },
  { name: "Université Cadi Ayyad de Marrakech", type: "university" },
  { name: "Université Ibn Zohr d'Agadir", type: "university" },
  { name: "Université Sidi Mohamed Ben Abdellah de Fès", type: "university" },
  { name: "Université Abdelmalek Essaâdi de Tétouan", type: "university" },
  { name: "Université Moulay Ismail de Meknès", type: "university" },
  { name: "Université Chouaib Doukkali d'El Jadida", type: "university" },
  { name: "Université Sultan Moulay Slimane de Beni Mellal", type: "university" },
  { name: "Université Ibn Tofaïl de Kénitra", type: "university" },
  { name: "Université Mohammed Premier d'Oujda", type: "university" },
  { name: "Université Hassan 1er de Settat", type: "university" },
  { name: "Université Moulay Abdellah de Guelmim-Oued Noun", type: "university" },
  { name: "Université Mohammed VI Polytechnique (UM6P)", type: "university" },
  { name: "Université Internationale de Rabat (UIR)", type: "university" },
  { name: "Université Al Akhawayn d'Ifrane", type: "university" },
  { name: "Université Euromed de Fès", type: "university" },
  { name: "École Nationale des Sciences Appliquées d'Agadir (ENSA Agadir)", type: "school" },
  { name: "École Nationale des Sciences Appliquées d'Al Hoceima (ENSA Al Hoceima)", type: "school" },
  { name: "École Nationale des Sciences Appliquées d'El Jadida (ENSA El Jadida)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Fès (ENSA Fès)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Kénitra (ENSA Kénitra)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Khouribga (ENSA Khouribga)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Marrakech (ENSA Marrakech)", type: "school" },
  { name: "École Nationale des Sciences Appliquées d'Oujda (ENSA Oujda)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Safi (ENSA Safi)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Tanger (ENSA Tanger)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Tétouan (ENSA Tétouan)", type: "school" },
  { name: "École Nationale des Sciences Appliquées de Berrechid (ENSA Berrechid)", type: "school" },
  { name: "École Nationale Supérieure d'Arts et Métiers de Meknès (ENSAM Meknès)", type: "school" },
  { name: "École Nationale Supérieure d'Arts et Métiers de Casablanca (ENSAM Casablanca)", type: "school" },
  { name: "École Nationale Supérieure d'Arts et Métiers de Rabat (ENSAM Rabat)", type: "school" },
  { name: "École Nationale Supérieure d'Électricité et de Mécanique de Casablanca (ENSEM Casablanca)", type: "school" },
  { name: "École Mohammadia d'Ingénieurs de Rabat (EMI Rabat)", type: "school" },
  { name: "École Hassania des Travaux Publics de Casablanca (EHTP Casablanca)", type: "school" },
  { name: "École Nationale Supérieure d'Informatique et d'Analyse des Systèmes de Rabat (ENSIAS Rabat)", type: "school" },
  { name: "Institut National des Postes et Télécommunications de Rabat (INPT Rabat)", type: "school" },
  { name: "Institut National de Statistique et d'Économie Appliquée de Rabat (INSEA Rabat)", type: "school" },
  { name: "École Supérieure des Industries du Textile et de l'Habillement de Casablanca (ESITH Casablanca)", type: "school" },
  { name: "Académie Internationale Mohammed VI de l'Aviation Civile de Casablanca (AIAC Casablanca)", type: "school" },
  { name: "Institut Agronomique et Vétérinaire Hassan II de Rabat (IAV Rabat)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Settat (FST Settat)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Tanger (FST Tanger)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Mohammedia (FST Mohammedia)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Marrakech (FST Marrakech)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Fès (FST Fès)", type: "school" },
  { name: "Faculté des Sciences et Techniques d'Errachidia (FST Errachidia)", type: "school" },
  { name: "Faculté des Sciences et Techniques d'Al Hoceima (FST Al Hoceima)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Beni Mellal (FST Beni Mellal)", type: "school" },
  { name: "Faculté des Sciences et Techniques d'El Jadida (FST El Jadida)", type: "school" },
  { name: "Faculté des Sciences et Techniques de Guelmim (FST Guelmim)", type: "school" },
];