import { Company } from "@/types/types";

export const universitiesSchools = [
  { "name": "Université Mohammed V de Rabat" },
  { "name": "Université Hassan II de Casablanca" },
  { "name": "Université Cadi Ayyad de Marrakech" },
  { "name": "Université Ibn Zohr d'Agadir" },
  { "name": "Université Sidi Mohamed Ben Abdellah de Fès" },
  { "name": "Université Abdelmalek Essaâdi de Tétouan" },
  { "name": "Université Moulay Ismail de Meknès" },
  { "name": "Université Chouaib Doukkali d'El Jadida" },
  { "name": "Université Sultan Moulay Slimane de Beni Mellal" },
  { "name": "Université Ibn Tofaïl de Kénitra" },
  { "name": "Université Mohammed Premier d'Oujda" },
  { "name": "Université Hassan 1er de Settat" },
  { "name": "Université Moulay Abdellah de Guelmim-Oued Noun" },
  { "name": "Université Mohammed VI Polytechnique (UM6P)" },
  { "name": "Université Internationale de Rabat (UIR)" },
  { "name": "Université Al Akhawayn d'Ifrane" },
  { "name": "Université Euromed de Fès" },
  { "name": "École Nationale des Sciences Appliquées d'Agadir (ENSA Agadir)" },
  { "name": "École Nationale des Sciences Appliquées d'Al Hoceima (ENSA Al Hoceima)" },
  { "name": "École Nationale des Sciences Appliquées d'El Jadida (ENSA El Jadida)" },
  { "name": "École Nationale des Sciences Appliquées de Fès (ENSA Fès)" },
  { "name": "École Nationale des Sciences Appliquées de Kénitra (ENSA Kénitra)" },
  { "name": "École Nationale des Sciences Appliquées de Khouribga (ENSA Khouribga)" },
  { "name": "École Nationale des Sciences Appliquées de Marrakech (ENSA Marrakech)" },
  { "name": "École Nationale des Sciences Appliquées d'Oujda (ENSA Oujda)" },
  { "name": "École Nationale des Sciences Appliquées de Safi (ENSA Safi)" },
  { "name": "École Nationale des Sciences Appliquées de Tanger (ENSA Tanger)" },
  { "name": "École Nationale des Sciences Appliquées de Tétouan (ENSA Tétouan)" },
  { "name": "École Nationale des Sciences Appliquées de Berrechid (ENSA Berrechid)" },
  { "name": "École Nationale Supérieure d'Arts et Métiers de Meknès (ENSAM Meknès)" },
  { "name": "École Nationale Supérieure d'Arts et Métiers de Casablanca (ENSAM Casablanca)" },
  { "name": "École Nationale Supérieure d'Arts et Métiers de Rabat (ENSAM Rabat)" },
  { "name": "École Nationale Supérieure d'Électricité et de Mécanique de Casablanca (ENSEM Casablanca)" },
  { "name": "École Mohammadia d'Ingénieurs de Rabat (EMI Rabat)" },
  { "name": "École Hassania des Travaux Publics de Casablanca (EHTP Casablanca)" },
  { "name": "École Nationale Supérieure d'Informatique et d'Analyse des Systèmes de Rabat (ENSIAS Rabat)" },
  { "name": "Institut National des Postes et Télécommunications de Rabat (INPT Rabat)" },
  { "name": "Institut National de Statistique et d'Économie Appliquée de Rabat (INSEA Rabat)" },
  { "name": "École Supérieure des Industries du Textile et de l'Habillement de Casablanca (ESITH Casablanca)" },
  { "name": "Académie Internationale Mohammed VI de l'Aviation Civile de Casablanca (AIAC Casablanca)" },
  { "name": "Institut Agronomique et Vétérinaire Hassan II de Rabat (IAV Rabat)" },
  { "name": "Faculté des Sciences et Techniques de Settat (FST Settat)" },
  { "name": "Faculté des Sciences et Techniques de Tanger (FST Tanger)" },
  { "name": "Faculté des Sciences et Techniques de Mohammedia (FST Mohammedia)" },
  { "name": "Faculté des Sciences et Techniques de Marrakech (FST Marrakech)" },
  { "name": "Faculté des Sciences et Techniques de Fès (FST Fès)" },
  { "name": "Faculté des Sciences et Techniques d'Errachidia (FST Errachidia)" },
  { "name": "Faculté des Sciences et Techniques d'Al Hoceima (FST Al Hoceima)" },
  { "name": "Faculté des Sciences et Techniques de Beni Mellal (FST Beni Mellal)" },
  { "name": "Faculté des Sciences et Techniques d'El Jadida (FST El Jadida)" },
  { "name": "Faculté des Sciences et Techniques de Guelmim (FST Guelmim)" }
];